# Generated by Django 4.1 on 2024-08-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tip', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
